<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemPenilaianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
           DB::table('item_penilaian')->insert([
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KQ',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KDSL',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A1',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'A2',
                'pernyataan' => fake()->sentence(rand(10, 30)),
                'versi' => 1,
                'nilai_aiken' => 1,
                'status' => 'valid',
                'isDigunakan' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
