<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemPenilaianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
           DB::table('item_penilaian')->insert([
            [
                'kode_kategori_penilaian' => 'PROF',
                'pernyataan' => 'Guru selalu hadir tepat waktu dan mempersiapkan kelas sebelum pelajaran dimulai',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PROF',
                'pernyataan' => 'Guru menjaga penampilan diri yang rapi dan profesional selama mengajar.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PROF',
                'pernyataan' => 'Guru menjaga sikap profesional dalam berinteraksi dengan siswa dan rekan sejawat',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PROF',
                'pernyataan' => 'Guru senantiasa memperbaharui pengetahuan dan keterampilan mengajarnya melalui pelatihan atau seminar.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PROF',
                'pernyataan' => 'Guru menjaga integritas profesi dalam menjalankan tugas sebagai guru maupun orang tua.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PROF',
                'pernyataan' => 'Guru menjaga integritas profesi dalam menjalankan tugas sebagai guru maupun orang tua.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KM',
                'pernyataan' => 'Guru mampu mempersiapkan materi pembelajaran yang sesuai dengan standar kurikulum.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KM',
                'pernyataan' => 'Guru menggunakan alat bantu pembelajaran yang mendukung pemahaman siswa.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KM',
                'pernyataan' => 'Guru menjelaskan gambaran besar tujuan pembelajaran di awal setiap sesi',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KM',
                'pernyataan' => 'Guru mampu menyampaikan materi pelajaran dengan jelas dan mudah dipahami oleh siswa',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PTP',
                'pernyataan' => 'Guru menggunakan perangkat teknologi seperti laptop atau proyektor untuk mendukung pembelajaran',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PTP',
                'pernyataan' => 'Guru memanfaatkan aplikasi pendidikan untuk meningkatkan interaktivitas siswa selama pembelajaran.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PTP',
                'pernyataan' => 'Guru mampu mengatasi masalah teknis yang muncul selama penggunaan teknologi dalam pembelajaran.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PTP',
                'pernyataan' => 'Guru mengajarkan siswa cara menggunakan teknologi secara etis dan bertanggung jawab..',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'PTP',
                'pernyataan' => 'Guru melatih siswa menggunakan aplikasi yang relevan dengan pembelajaran.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'MK',
                'pernyataan' => 'Guru memiliki kemampuan untuk menjaga kedisiplinan siswa selama kegiatan belajar.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'MK',
                'pernyataan' => 'Guru memastikan setiap siswa fokus dan terlibat dalam kegiatan pembelajaran.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'MK',
                'pernyataan' => 'Guru mampu mengelola berbagai situasi yang terjadi dalam kelas dengan efektif.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'MK',
                'pernyataan' => 'Guru memberikan instruksi yang jelas sehingga siswa tahu apa yang harus dilakukan.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'MK',
                'pernyataan' => 'Guru memiliki metode yang efektif untuk mengatasi gangguan yang terjadi di kelas.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KS',
                'pernyataan' => 'Guru aktif mendengarkan dan memberi perhatian saat siswa berbicara.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KS',
                'pernyataan' => 'Guru memfasilitasi diskusi yang terbuka dan membangun kepercayaan diri siswa',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KS',
                'pernyataan' => 'Guru memberi tanggapan yang membangun terhadap pertanyaan dan komentar siswa',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KS',
                'pernyataan' => 'Guru menggunakan bahasa yang sesuai dengan usia dan tingkat pemahaman siswa.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'KS',
                'pernyataan' => 'Guru berbicara dengan nada suara yang jelas dan bisa didengar oleh semua siswa di kelas.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'IOT',
                'pernyataan' => 'Guru melakukan komunikasi rutin dengan orang tua untuk melaporkan perkembangan akademik siswa.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'IOT',
                'pernyataan' => 'Guru melibatkan orang tua dalam kegiatan sekolah yang berhubungan dengan perkembangan siswa.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'IOT',
                'pernyataan' => 'Guru menyediakan waktu untuk bertemu dengan orang tua yang ingin mendiskusikan kemajuan siswa.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'IOT',
                'pernyataan' => 'Guru menyarankan orang tua untuk melibatkan diri dalam kegiatan belajar di rumah.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kategori_penilaian' => 'IOT',
                'pernyataan' => 'Guru berkomunikasi dengan orang tua mengenai prestasi akademik dan kegiatan ekstrakurikuler siswa.',
                'versi' => 1,
                'nilai_aiken' => 0,
                'status' => 'tidak_valid',
                'isDigunakan' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
